 // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnpkVcpDLgMkeu64ZLS-A70lsPlzzxO0g',
    appId: '1:212470707403:web:1d54a69616164bdf09d74e',
    messagingSenderId: '212470707403',
    projectId: 'ecomerce-bcd3b',
    authDomain: 'ecomerce-bcd3b.firebaseapp.com',
    storageBucket: 'ecomerce-bcd3b.firebasestorage.app',
    measurementId: 'G-QKFJYZ06DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvcEfJ_PVTikOHKqZqndgLVbkhaWzgW0s',
    appId: '1:212470707403:android:77669bee71be844309d74e',
    messagingSenderId: '212470707403',
    projectId: 'ecomerce-bcd3b',
    storageBucket: 'ecomerce-bcd3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGetNAq_rRvR0lTZdGHdxDOwUTHmWPlOI',
    appId: '1:212470707403:ios:54ddd7415562292909d74e',
    messagingSenderId: '212470707403',
    projectId: 'ecomerce-bcd3b',
    storageBucket: 'ecomerce-bcd3b.firebasestorage.app',
    iosBundleId: 'com.example.flutterEjercicio1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGetNAq_rRvR0lTZdGHdxDOwUTHmWPlOI',
    appId: '1:212470707403:ios:54ddd7415562292909d74e',
    messagingSenderId: '212470707403',
    projectId: 'ecomerce-bcd3b',
    storageBucket: 'ecomerce-bcd3b.firebasestorage.app',
    iosBundleId: 'com.example.flutterEjercicio1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnpkVcpDLgMkeu64ZLS-A70lsPlzzxO0g',
    appId: '1:212470707403:web:618309cf2392d06e09d74e',
    messagingSenderId: '212470707403',
    projectId: 'ecomerce-bcd3b',
    authDomain: 'ecomerce-bcd3b.firebaseapp.com',
    storageBucket: 'ecomerce-bcd3b.firebasestorage.app',
    measurementId: 'G-F55YSGMC9S',
  );
}
